### ISSUE TITLE
How to disable the smart semi-colon insertion?

### ISSUE THREAD

**Issue by dcousens** [rstacruz/vim-closer#11]
I have a JS file with 1 line (of a few hundred) ending with `;`,  and suddenly editing that file has become frustrating (ha).

Is it possible to globally disable the smart semi-colon insertion?
It does seem to cover >99% of cases,  alas.

**Comment by dcousens** [comment]
``` js
var a = {

}
// sneaky comment ending in ;

var b = {
  |
}; // :(
```

**Comment by rstacruz** [comment]
Ack, there's no "public" way for this, but you can probably get away with doing:

```vim
let b:closer_no_semi = 0
```

This will (probably) disable it for the current buffer.

**Comment by dcousens** [comment]
@rstacruz to clarify,  incase you want to file this as a bug.  The snippet above is verbatim.  A *comment* ending in `;` triggers the ASI.
