### ISSUE TITLE
Doesn't work with nvim-compe

### ISSUE THREAD

**Issue by heyitscassio** [rstacruz/vim-closer#33]
Me and the author couldn't find a way to make both of them work, see the issue opened by me in their repos: https://github.com/hrsh7th/nvim-compe/issues/262

**Comment by heyitscassio** [comment]
by changing the definition of `CloserClose` to `imap <script> <Plug>CloserClose <CR><SID>CloserClose` fixes the issue. I think renaming that expression to `CloserCr` and mapping it to `<CR>` makes more sense then needing to map `<CR>` to itself and `CloserClose`.

**Comment by rstacruz** [comment]
That's awesome, can anyone else confirm this fix works for them?

**Comment by rstacruz** [comment]
I tried it this:

```diff
 if maparg("<Plug>CloserClose") == ""
   inoremap <silent> <SID>CloserClose <C-R>=closer#close()<CR>
-  imap <script> <Plug>CloserClose <SID>CloserClose
+  imap <script> <Plug>CloserClose <CR><SID>CloserClose
 endif

```

and it doesn't quite work:

```
hello(<CR>
```

becomes

```
hello(

  |
```

**Comment by rstacruz** [comment]
btw, you might also want to try changing the order of plugins. There's some code in vim-closer to try and play nice with other plugins that rebind `<cr>`. Try loading vim-closer *after* nvim-compe.

**Comment by heyitscassio** [comment]
vim-closer doesn't play nice with compe, loading it after of before. I managed to make it work with the following modifications and configurations

In vim-closer:
```viml
if exists("g:closer_autoloaded") | finish | endif
let g:closer_autoloaded=1

if ! exists("g:closer_dont_map") | let g:closer_dont_map=0 | endif

if maparg("<Plug>CloserClose") == ""
  inoremap <silent> <SID>CloserClose <C-R>=closer#close()<CR>
  imap <script> <Plug>CloserClose <SID>CloserClose
endif

"
" Enables closer for the current buffer.
"

function! closer#enable()
  if ! exists('b:closer_flags') | return | endif
  let b:closer = 1
  let oldmap = maparg('<CR>', 'i')

  if ! g:closer_dont_map
	  if oldmap =~# 'CloserClose'
		" already mapped. maybe the user was playing with `set ft`
	  elseif oldmap != ""
		exe "imap <CR> ".oldmap."<Plug>CloserClose"
	  else
		imap  <CR> <Plug>CloserCR
	  endif
  endif
endfunction
```

So by setting `g:closer_dont_map` to 1 I can force it to not rebind `<CR>` so i can bind it to a function that will handle compe and closer. Vim-endwise behaves like that when setting `g:endwise_no_mappings`.

In my configuration (in lua, but it is doable in viml too)
```lua
local opts = {expr = true, silent = true}
local mappings = {
	{"i", "<CR>", "v:lua.compeCR()", opts},
	{"i", "<Tab>", "v:lua.tab_complete()", opts},
	{"s", "<Tab>", "v:lua.tab_complete()", opts},
	{"i", "<S-Tab>", "v:lua.s_tab_complete()", opts},
	{"s", "<S-Tab>", "v:lua.s_tab_complete()", opts}
}

...

local t = function(str)
	return vim.api.nvim_replace_termcodes(str, true, true, true)
end

_G.compeCR = function()
	if vim.fn.pumvisible() == 1 then
		vim.fn['compe#confirm']('<CR>')
	else
		return t "<CR><Plug>CloserClose"
	end
end
```

**Comment by rstacruz** [comment]
There's now an option to turn off key bindings with #34, hope that helps!

**Comment by heyitscassio** [comment]
Yes, i opened it. It's all working now.

**Comment by samhh** [comment]
@toniz4 What's your config looking like now? I'm still seeing the issue if I use the following:

```vim
let g:closer_no_mappings=1

inoremap <silent><expr> <cr> compe#confirm({ 'keys': "\<cr>\<plug>CloserClose", 'mode': '' })
```

**Comment by heyitscassio** [comment]
I was having problems with that too, i think it is a problem with compe. In my pull request I showed a example in lua. But in #30 @dialtone showed a example that now works

```viml
imap <expr><silent> <CR> pumvisible() ? complete_info()["selected"] != "-1" ?
			\ "\<Plug>(completion_confirm_completion)" : "\<C-E>\<CR>" :
			\ "\<CR>"<Plug>CloserClose
```

**Comment by samhh** [comment]
Hmm, in insert mode I get `E15: Invalid expression`. :thinking:
